### ISSUE TITLE
Possibility to disable registration.

### ISSUE THREAD

**Issue by Tiritibambix** [Casvt/Noted#27]
I know you're planning on implementing an Admin user account / panel to handle things on Noted.

When it's done, it'd be great to have the possibility to choose to disable registration or not. I don't want anybody on my LAN to be able to create an account if I don't want to.

This could be extra handy for people willing to publicly expose Noted.

**Comment by Casvt** [comment]
Linked to #1 

Features of the admin panel will include: disabling user registration (though the admin can always add users from the admin panel), user management (changing passwords, deleting users, etc.) and hosting settings (host, port).
