### ISSUE TITLE
Possibility to add a color to reminders.

### ISSUE THREAD

**Issue by Tiritibambix** [Casvt/Noted#28]
This will be really helpful when tagging and static reminders will be implemented and will add a nice visual aid to sorting reminders at a glance.

**Comment by Casvt** [comment]
Added feature. Will be included in the next release. Thank you for requesting :)

![image](https://user-images.githubusercontent.com/88994465/215283443-39ef1b23-818d-4f63-8534-0d116c105d48.png)

**Comment by Tiritibambix** [comment]
Awesome, thank you :)
