### ISSUE TITLE
Test button for notification

### ISSUE THREAD

**Issue by Antoine2tt** [Casvt/Noted#29]
Hi 😄 

I think that it could be good to have a button to test if notifications are working ! 

Thanks

**Comment by ItsNoted** [comment]
> Hi 😄
> 
> I think that it could be good to have a button to test if notifications are working !
> 
> Thanks

This is something we discussed already. But we think having a "send now" button is more appropriate. This way you can send messages you create on demand.

**Comment by Casvt** [comment]
@ItsNoted is referring to issue #9. I actually disagree and think this is a good feature to add. Static reminders (what @ItsNoted and issue #9 refer to) are not a feasible way to fulfil this request.

**Comment by ItsNoted** [comment]
> @ItsNoted is referring to issue #9. I actually disagree and think this is a good feature to add. Static reminders (what @ItsNoted and issue #9 refer to) are not a feasible way to fulfil this request.

Ah yes I misunderstood his inquiry. Having a test button on the create reminder page would prove useful!

**Comment by Casvt** [comment]
I've implemented this feature and it will be included in the next release. Thank you for requesting.
