### ISSUE TITLE
selfhosted ntfy with auth not working ¿?

### ISSUE THREAD

**Issue by rubenixnagios** [Casvt/Noted#34]
**Description of the bug**
selfhosted ntfy with auth not working as expected / working from container

**To Reproduce**
have a selfhosted ntfy with auth but not working when I set up a reminder
working if I send the notification from inside the container

heres the command i send from the container that works:

apprise -vv -t "Test Message Title" -b "Test Message Body" \
ntfys://username:"password"@ntfy.mydomain.com/Mytopic

--> Have to escape as theres a special character on password 

so, thats what I set on the Notification Services:
ntfys://username:"password"@ntfy.mydomain.com/Mytopic

nothing sent when I press on test or I set up a reminder.

**Expected behaviour**
get the notification

**Screenshots**
NA

**Version info**
 - OS: debian / docker
 - Browser: NA
 - Noted Version: todays latest
 - Python Version: [e.g. V3.7]

**Additional context**
Can somebody reproduce this? Something bad on my sintax in the Notification Services section?

thanks so much for this nice piece of work!

**Comment by Casvt** [comment]
Probably has to do with the escaping. I'll check it out. In the mean time: does it work when the string is the following?
```
ntfys://username:\"password\"@ntfy.mydomain.com/Mytopic
```
Instead of:
```
ntfys://username:"password"@ntfy.mydomain.com/Mytopic
```

**Comment by rubenixnagios** [comment]
not working:
`ntfys://username:\"password\"@ntfy.mydomain.com/Mytopic`
nor
`ntfys://username:\"password"\@ntfy.mydomain.com/Mytopic`
get this:
`>`

**Comment by rubenixnagios** [comment]
message sent to ntfy.sh instead if that helps

**Comment by Casvt** [comment]
In the Noted web-ui, when you go to the "Notification services" tab and edit the ntfy service you've setup, can you escape the quotes in the url? Escaping being `"` -> `\"`.

Then save, and use the test button when adding a reminder to see if it works or not.

**Comment by rubenixnagios** [comment]
test it right now, notification not sent to my selfhosted ntfy but it sends to ntfy.sh instead...
my ntfy service works, it has to be something with the escaping, Im pretty sure

**Comment by rubenixnagios** [comment]
from inside container does not work either with the escaping you suggested:
` !\"@ntfy.mydomain.com/MyTopic : event not found`

**Comment by rubenixnagios** [comment]
just an update here: tried also with single quotes and makes no difference...

also tried tro escape it like `'\` or `\'` same result (notification sent to ntfy.sh and not to my selhosted ntfy

**Comment by Casvt** [comment]
The quotes aren't needed. Edit the notification service in the UI and remove the quotes from the url. It should work just fine without them.

**Comment by rubenixnagios** [comment]
sorry for the delay here, been away; indeed it works.
dunno what happened here but I tough I tried with no quotes as my first attempt...
Thanks for your time mate, time to add reminders!!
