### ISSUE TITLE
Image Docker arm64

### ISSUE THREAD

**Issue by gturyz** [Casvt/Noted#37]
Hello,

The title says it all ^^'

**Comment by Casvt** [comment]
No it doesn't? You want a docker image for arm devices? Doesnt the current one suffice for arm devices?

**Comment by gturyz** [comment]
The current image on the dockerhub mrcas/mind, is only available for amd64 platforms. For ease of use of the image on arm64 platforms, is it possible to add an arm64 version of the image?

Is there something I don't understand?

**Comment by Casvt** [comment]
Oh okay I can make one for arm I think

**Comment by gturyz** [comment]
Thank you ^^

**Comment by pcgeek86** [comment]
That would be awesome. I use Docker on ARM64 devices, like the ODROID M1, for self-hosting server apps (InfluxDB, Uptime Kuma, etc.). Adding MIND to that list would be helpful.

**Comment by ghost** [comment]
To create a builder:
`docker buildx create --name multiarch --use`

To create a multi-arch image for MacOS(armv7), RPI(arm64), and normal 64bit cpu's:
`docker buildx build --push --platform linux/amd64,linux/arm64,linux/arm/v7 --tag [your tag]`

Docs: https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/
