### ISSUE TITLE
Support hosting on specific url path

### ISSUE THREAD

**Issue by marekhanzlik** [Casvt/Noted#38]
Right now you have to host this app on `somedomain.com` and it is impossible to set it to run at `somedomain.com/mind` because static files are expected on certain location. If you bypass this on reverse proxy side and fix the fetching of static CSS etc. you still have problem with login cause it calls POST to `/`  
Please allow to specify different app path than `/`

**Comment by Casvt** [comment]
Basically, you want a URL prefix option. That's possible for sure :)

**Comment by Casvt** [comment]
Request completed. You can now go into the `MIND.py` file and change the value of `URL_PREFIX`. This feature will also be included in the next release and docker container.

Note that this hosting option will be included in the features of #1. You will be able to configure the host and port in the admin panel and now also the url prefix.

**Comment by Casvt** [comment]
New release is out and so is a new docker container.
