### ISSUE TITLE
Default notification service.

### ISSUE THREAD

**Issue by Tiritibambix** [Casvt/Noted#56]
**Is your feature request related to a problem? Please describe.**
I have Discord and Ntfy as notification services. When creating a new reminder, Discord is selected by default

**Describe the solution you'd like**
An option in the settings to set a default notification service.

**Additional context**
That'd be great :)

**Comment by Casvt** [comment]
Added and will be included in the next release. A new setting is added where you can select the notification service that is selected by default every time you add a reminder, static reminder or template. The setting is client specific: it applies to the client so the setting is different from client to client. This was done on purpose with the following reasoning:

Often, when people set reminders on a device, they want to receive the reminder on the same device they set it on. So if you set a reminder on your phone, you most likely also want to receive it on your phone. On your phone, you can set the default notification service to the one for your phone, while on your computer you set it to the one for your computer.

**Comment by Tiritibambix** [comment]
That's awesome. Can't wait :)
