### ISSUE TITLE
Cannot Delete Notification Service

### ISSUE THREAD

**Issue by Lord0fBytes** [Casvt/Noted#57]
**Description of the bug**
Trying to delete a notification service it just turns the trash icon red, but doesn't remove the service. Clicking it again does nothing as well. 

**To Reproduce**
1. Go to Notification Services
2. Click on Trash can icon
3. See error

**Expected behaviour**
I assume a pop-up might come up to ask you to delete it or it would just be removed. 

**Screenshots**
![Screen Shot 2023-07-26 at 7 50 28 PM](https://github.com/Casvt/MIND/assets/7501413/09db6050-c398-43da-8b79-acbadeb1eb2e)

**Version info**
 - OS: Docker Compose (running on Debian 11)
 - Browser: Chrome/Brave
 - MIND Version: V1.3.2
 - Python Version: 3.8.16

**Comment by Lord0fBytes** [comment]
Network data from the browser redacted port numbers):
![Screen Shot 2023-07-26 at 7 58 18 PM](https://github.com/Casvt/MIND/assets/7501413/40da05d6-ebf9-48e5-a1ae-41012b4b7cb0)

**Comment by Casvt** [comment]
Can you click on the request in the dev panel and show the payload?

**Comment by Lord0fBytes** [comment]
Is this what you are looking for: 
<img width="675" alt="Screenshot 2023-07-27 at 2 29 53 PM" src="https://github.com/Casvt/MIND/assets/7501413/42cd1b46-0d41-4c79-b0ed-9449d8efabf0">

**Comment by Lord0fBytes** [comment]
or this:
<img width="721" alt="Screenshot 2023-07-27 at 2 33 55 PM" src="https://github.com/Casvt/MIND/assets/7501413/30f07bbb-95ea-40de-a6e1-f0c02e304508">

**Comment by Casvt** [comment]
Okay thanks

**Comment by Casvt** [comment]
@Lord0fBytes It could be that MIND is not allowing you to delete it because the service is still in use. When deleting the notification service, and the button turns red, hover your mouse over the button and see what it says.

**Comment by Lord0fBytes** [comment]
Ya, I just saw the docker logs were saying it is still being used by another service. I was able to delete it now.
