### ISSUE TITLE
Telegram Notifications

### ISSUE THREAD

**Issue by VlaK0r** [Casvt/Noted#60]
Hello!
Thank you for your work.

I can't configure it Telegram Notifications.
I do everything according to the instructions https://github.com/caronc/apprise/wiki/Notify_telegram

What could be the problem?

![image](https://github.com/Casvt/MIND/assets/77666575/094b8151-73f5-46ab-b9c4-5e0d89ca1f31)

**Comment by Casvt** [comment]
Fix will be included in next release. For now, you can just use the "Custom URL" option (first entry in the list of supported services when adding one). For the "Apprise URL" field, enter `tgram://6567703579:AAHAIH9h7WZT_E3jVuc4PzM6lbfHvwBujy4`.
