### ISSUE TITLE
Static Trigger button broken

### ISSUE THREAD

**Issue by DANW999** [Casvt/Noted#62]
All of a sudden the trigger button for all and any static reminders has stopped working, even new ones I create. This happened right after I tried to add telegram emoticons into a reminder using Unicode.

  File "/app/backend/static_reminders.py", line 259, in trigger_reminder
    logging.info(f'Triggering static reminder {self.id}')
AttributeError: 'StaticReminders' object has no attribute 'id'

**To Reproduce**

1. Log into Mind Reminders
2. Click on any reminder under static or create a new one.
3. Press trigger - nothing happens
4. In the logs it says:-

  File "/app/frontend/api.py", line 770, in api_get_static_reminder
    reminders.trigger_reminder(s_id)
  File "/app/backend/static_reminders.py", line 259, in trigger_reminder
    logging.info(f'Triggering static reminder {self.id}')
AttributeError: 'StaticReminders' object has no attribute 'id'
[2023-08-27 19:37:27][waitress-6][INFO] Deleting static reminder 1

**Expected behaviour**
When pressing trigger it should just sent the static reminder to the endpoint.

**Screenshots**
N/A

**Version info**
 - OS: Docker
 - Browser: Tried on both Firefox and Chrome
 - MIND Version: mrcas/mind:v1.3.3
 - Python Version: N/A

**Additional context**
N/A

**Comment by DANW999** [comment]
So I restored an earlier version of my sqlite database an the trigger for static reminders still does not work. So I don't even think this had anything to do with me adding unicode to message. Same error message.

**Comment by Casvt** [comment]
Fixed. Will be included in next release.

**Comment by DANW999** [comment]
Thank you @Casvt I look forward to it.
