### ISSUE TITLE
Cannot enter notification service

### ISSUE THREAD

**Issue by kingb2019** [Casvt/Noted#63]
**Description of the bug**
On the Notification Services menu, no matter which service I use I cannot complete the Add process. I can choose the service, fill out the required info but when I click Add or Test nothing happens. Cancel will cancel the submission and I can start over. 

**To Reproduce**

1. Go to '...' Notification Services
2. Click on '....' Pushover
3. Scroll down to '....' Enter in required info
4. See error - Click Add or Test and nothing happens

**Expected behaviour**

Entry would be  submitted and able to use.

**Screenshots**

**Version info**
 - OS: [e.g. iOS] - Docker running on Ubuntu 20.04
 - Browser: [e.g. chrome, safari] Chrome & Edge
 - MIND Version: [e.g. V1.0.0] Latest
 - Python Version: [e.g. V3.7] Whatever came with MIND in Docker

**Additional context**

**Comment by Casvt** [comment]
Does it work when you enter a custom URL (first entry in service list)?

**Comment by kingb2019** [comment]
> Does it work when you enter a custom URL (first entry in service list)?

No, same issue. Click the buttons and no change.

**Comment by Casvt** [comment]
Do the logs say anything?

**Comment by kingb2019** [comment]
> Do the logs say anything?

Good call. The logs said invalid URL when I tried the custom URL. I was typing power instead of pover. I corrected the URL and it worked! 

Odd though that the Pushover integration did not generate any logs whatsoever, even when I tried again. 

Thanks for guiding me to look into this. All is working now with custom URL.

**Comment by Casvt** [comment]
Yeah but it should still be fixed that could only add it using custom URL
