### ISSUE TITLE
packages update

### ISSUE THREAD

**Issue by abuhamsa** [Casvt/Noted#66]
**Is your feature request related to a problem? Please describe.**
The used packages could need some updates but if you build it from scratch there are breaking changes in the packages

**Describe the solution you'd like**
Update code that the newest packages work

**Additional context**
I think there are some problem with flask and Werkzeug. 
If you go up to debian 12 (bookworm) you have to take care of venv stuff: https://pythonspeed.com/articles/activate-virtualenv-dockerfile/

**Comment by Casvt** [comment]
In the development branch, there is already a fix for flask v3. So just build from the dev branch instead of the main branch.
