### ISSUE TITLE
Docker contrainer won't start after upgrading to v1.4.0

### ISSUE THREAD

**Issue by dhanadhan** [Casvt/Noted#73]
**Description of the bug**
Watchtower automatically upgraded the Mind v1.4.0 container and it's been down since. It was working fine before. I read the new version notes, but it doesn't say to update anything. So I assume simply upgrading the docker container would work. 

**Logs**

> [22:57:02][INFO] Starting up MIND
> Traceback (most recent call last):
>   File "/app/MIND.py", line 65, in <module>
>     MIND()
>   File "/app/MIND.py", line 44, in MIND
>     setup_db()
>   File "/app/backend/db.py", line 395, in setup_db
>     set_log_level(get_setting('log_level'), clear_file=False)
>   File "/app/backend/logging.py", line 122, in set_log_level
>     LOGGER.setLevel(level)
>   File "/usr/local/lib/python3.8/logging/__init__.py", line 1421, in setLevel
>     self.level = _checkLevel(level)
>   File "/usr/local/lib/python3.8/logging/__init__.py", line 198, in _checkLevel
>     raise ValueError("Unknown level: %r" % level)
> ValueError: Unknown level: '20'

**Version info**
 - Docker on linux
 - MIND Version: v1.4.0

**Additional context**
I stopped getting reminders since yesterday. I just noticed that there is a new version out and my container has not been running since the upgrade. I can't even get to the web page since the container won't start.

**Comment by ichbinrodolf** [comment]
Same issue here, seems upgrade to v1.4.0 is the cause indeed

**Comment by Casvt** [comment]
Fixed. Just re-pull the latest image (v1.4.0) and it should work
