### ISSUE TITLE
Supporting a reminder to add multiple times

### ISSUE THREAD

**Issue by Codefor4learn** [Casvt/Noted#78]
For example, I need to set up a reminder for going to and from work. My working hours are 9am and my off hours are 6pm. I would like to send an email to remind me to clock in from Monday to Friday. This can be set in one reminder without the need to set multiple reminders

**Comment by Casvt** [comment]
This is just a more complicated time setup. One reminder that runs every work day at 9am and one reminder that runs every work day at 6pm.

You need seperate reminders anyway for a different message: "Start work" and "Finish work".

Could you describe better what you would like to see changed or alternatively what exactly you want to do what you can't currently?

**Comment by Codefor4learn** [comment]
![image](https://github.com/Casvt/MIND/assets/74418619/ec56f30b-0fa3-4b33-b9b9-c37e4b66f6f5)
I hope these two can be implemented in one reminder

**Comment by Codefor4learn** [comment]
There is another situation, which is more important. I hope to be reminded multiple times within a day because I am afraid that I will be busy and ignore it when  first remind .

**Comment by Casvt** [comment]
This can be fixed by implementing cron, which makes this a "duplicate" of #83
