### ISSUE TITLE
Notification in the form of an RSS Feed

### ISSUE THREAD

**Issue by VlaK0r** [Casvt/Noted#81]
Hello!
Thank you for your hard work!

Please tell me, is it possible to use your service to send a notification in the form of an RSS Feed?

**Comment by Casvt** [comment]
MIND uses the [apprise](https://github.com/caronc/apprise) module to send the notifications, which means that the supported methods of sending the notification is on that module. So you should ask there, but a quick search seems to suggest that it is not possible. You should check there though.
