### ISSUE TITLE
freemobile service not available

### ISSUE THREAD

**Issue by LiloBzH** [Casvt/Noted#85]
Hi !

It doesn't work with "freemobile" via custom url
 
https://github.com/caronc/apprise/wiki/Notify_freemobile

```
:40m[22:18:12][ERROR] Unparseable URL freemobile://abc123@98765
:40m[22:18:12][WARNING] This key in the API request has an invalid value: url = freemobile://abc123@98765
```

Thanks !

**Comment by LiloBzH** [comment]
ok found why . Apprise version is old

```
root@6c2176dae176:/app# pip list
Package            Version
apprise            1.7.4
```

After tests, it's work with apprise 1.8.0 but MIND dont know how user it i  suppose

`:40m[00:06:00][WARNING] Failed to send Free Mobile notification: Bad Request - Unsupported Parameters., error=400.`

in shell of container 

```
root@6c2176dae176:/app# apprise -vv -t "Test Message Title" -b "Test Message Body" "freemobile://0000000@azertui"
2024-05-17 00:07:46,578 - INFO - Sent Free Mobile notification.
```

**Comment by Casvt** [comment]
Sooo this all comes down to just updating the apprise dependency version.

**Comment by Casvt** [comment]
Updated Apprise version in V1.4.1
