### ISSUE TITLE
Unparseable JSON URL

### ISSUE THREAD

**Issue by dviry** [Casvt/Noted#90]
I am not sure if this happens in MIND or in apprise, but sending a custom JSON notification fails if the url starts with a number (like microsoft dev tunnels do). This is using the latest docker instance.

Posting to my local /api/notificationservices/test the following json body:

```
{
    "url": "json://5t4m59hl-34343.euw.devtunnels.ms"
}
```

Shows in the docker log the following:

[ERROR] Unparseable JSON URL json://5t4m82hl-33333.euw.devtunnels.ms
[WARNING] This key in the API request has an invalid value: url = json://5t4m82hl-33333.euw.devtunnels.ms

This works fine if using a url that starts with an alphanumeric letter.

**Comment by Casvt** [comment]
I checked, this is a bug in Apprise, not MIND. Please make an issue there.

**Comment by dviry** [comment]
This has now been fixed on the upstream repository - when do you think it will be available in your docker image?

Thanks!

**Comment by Casvt** [comment]
Updated Apprise in V1.4.1
